name: Build and Test

on:

env:
  BUILD_NUMBER: 4.0.2.${{ github.run_number }}
  DOTNET_VERSION: 3.1.x
  SOLUTION_PATH: ./src/GuardAgainstLib.sln
  PROJECT_PATH: ./src/GuardAgainstLib/GuardAgainstLib.csproj
  CONFIGURATION: Release
  ARITFACT_PATH: ./dist

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Clean
        run: dotnet clean --configuration ${{ env.CONFIGURATION }} --nologo ${{ env.SOLUTION_PATH }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore --nologo /p:BuildNumber=${{ env.BUILD_NUMBER }} -p:Version=${{ env.BUILD_NUMBER }} ${{ env.SOLUTION_PATH }}

      - name: Test
        run: dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore --no-build --verbosity normal --nologo ${{ env.SOLUTION_PATH }}

      #- name: Publish
      #  run: dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --no-restore --nologo --output ${{ env.ARITFACT_PATH }}

      - name: Pack
        run: dotnet pack
          ${{ env.PROJECT_PATH }}
          --configuration ${{ env.CONFIGURATION }}
          --no-build
          --no-restore
          --nologo
          --verbosity Detailed
          /p:Version=${{ env.BUILD_NUMBER }}
          /p:PackageVersion=${{ env.BUILD_NUMBER }}
          --output ${{ env.ARITFACT_PATH }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ${{ env.ARITFACT_PATH }}/GuardAgainst.*.nupkg
