name: build & test

on:
  push:
  pull_request:
    branches:
      - master

env:
  BUILD_NUMBER: 4.0.2.${{ github.run_number }}
  DOTNET_VERSION: 3.1.x
  SOLUTION_PATH: ./src/GuardAgainstLib.sln
  PROJECT_PATH: ./src/GuardAgainstLib/GuardAgainstLib.csproj
  CONFIGURATION: Release

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - uses: actions/checkout@v2
      # - name: setup dotnet core
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}
      # - name: clean
      #   run: dotnet clean
      #     --configuration ${{ env.CONFIGURATION }}
      #     --nologo
      #     ${{ env.SOLUTION_PATH }}
      # - name: build
      #   run: dotnet build
      #     --configuration ${{ env.CONFIGURATION }}
      #     --verbosity detailed
      #     --no-incremental
      #     --nologo
      #     /p:BuildNumber=${{ env.BUILD_NUMBER }}
      #     /p:Version=${{ env.BUILD_NUMBER }}
      #     ${{ env.SOLUTION_PATH }}
      # - name: test
      #   run: dotnet test
      #     --configuration ${{ env.CONFIGURATION }}
      #     --verbosity detailed
      #     --no-restore
      #     --no-build
      #     --verbosity normal
      #     --nologo
      #     ${{ env.SOLUTION_PATH }}
